#!/bin/sh

wget -O Bands_Homo_sapiens_Ensembl_Marton 'http://www.ensembl.org/biomart/martservice?query=<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Query><Query  virtualSchemaName = "default" formatter = "TSV" header = "0" uniqueRows = "0" count = "" datasetConfigVersion = "0.6" ><Dataset name = "hsapiens_gene_ensembl" interface = "default" ><Attribute name = "chromosome_name" /><Attribute name = "band" /><Attribute name = "ensembl_gene_id" /></Dataset></Query>'

wget -O Bands_Homo_sapiens_Uniprot_Marton 'http://www.ensembl.org/biomart/martservice?query=<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Query><Query  virtualSchemaName = "default" formatter = "TSV" header = "0" uniqueRows = "0" count = "" datasetConfigVersion = "0.6" ><Dataset name = "hsapiens_gene_ensembl" interface = "default" ><Attribute name = "chromosome_name" /><Attribute name = "band" /><Attribute name = "uniprot_genename" /></Dataset></Query>'

wget -O Bands_Homo_sapiens_Genesymbol_Marton 'http://www.ensembl.org/biomart/martservice?query=<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Query><Query  virtualSchemaName = "default" formatter = "TSV" header = "0" uniqueRows = "0" count = "" datasetConfigVersion = "0.6" ><Dataset name = "hsapiens_gene_ensembl" interface = "default" ><Attribute name = "chromosome_name" /><Attribute name = "band" /><Attribute name = "hgnc_symbol" /></Dataset></Query>'

wget -O Bands_Gallus_gallus_Ensembl_Marton 'http://www.ensembl.org/biomart/martservice?query=<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Query><Query  virtualSchemaName = "default" formatter = "TSV" header = "0" uniqueRows = "0" count = "" datasetConfigVersion = "0.6" ><Dataset name = "ggallus_gene_ensembl" interface = "default" ><Attribute name = "chromosome_name" /><Attribute name = "band" /><Attribute name = "ensembl_gene_id" /></Dataset></Query>'

wget -O Bands_Gallus_gallus_Ensembl_Marton 'http://www.ensembl.org/biomart/martservice?query=<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Query><Query  virtualSchemaName = "default" formatter = "TSV" header = "0" uniqueRows = "0" count = "" datasetConfigVersion = "0.6" ><Dataset name = "ggallus_gene_ensembl" interface = "default" ><Attribute name = "chromosome_name" /><Attribute name = "band" /><Attribute name = "uniprot_genename" /></Dataset></Query>'

wget -O Bands_Gallus_gallus_Ensembl_Marton 'http://www.ensembl.org/biomart/martservice?query=<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Query><Query  virtualSchemaName = "default" formatter = "TSV" header = "0" uniqueRows = "0" count = "" datasetConfigVersion = "0.6" ><Dataset name = "ggallus_gene_ensembl" interface = "default" ><Attribute name = "chromosome_name" /><Attribute name = "band" /><Attribute name = "hgnc_symbol" /></Dataset></Query>'

wget -O Bands_Pan_troglodytes_Ensembl_Marton 'http://www.ensembl.org/biomart/martservice?query=<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Query><Query  virtualSchemaName = "default" formatter = "TSV" header = "0" uniqueRows = "0" count = "" datasetConfigVersion = "0.6" ><Dataset name = "ptroglodytes_gene_ensembl" interface = "default" ><Attribute name = "chromosome_name" /><Attribute name = "band" /><Attribute name = "ensembl_gene_id" /></Dataset></Query>'

wget -O Bands_Pan_troglodytes_Ensembl_Marton 'http://www.ensembl.org/biomart/martservice?query=<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Query><Query  virtualSchemaName = "default" formatter = "TSV" header = "0" uniqueRows = "0" count = "" datasetConfigVersion = "0.6" ><Dataset name = "ptroglodytes_gene_ensembl" interface = "default" ><Attribute name = "chromosome_name" /><Attribute name = "band" /><Attribute name = "uniprot_genename" /></Dataset></Query>'

wget -O Bands_Pan_troglodytes_Ensembl_Marton 'http://www.ensembl.org/biomart/martservice?query=<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Query><Query  virtualSchemaName = "default" formatter = "TSV" header = "0" uniqueRows = "0" count = "" datasetConfigVersion = "0.6" ><Dataset name = "ptroglodytes_gene_ensembl" interface = "default" ><Attribute name = "chromosome_name" /><Attribute name = "band" /><Attribute name = "hgnc_symbol" /></Dataset></Query>'

wget -O Bands_Macaca_mulatta_Ensembl_Marton 'http://www.ensembl.org/biomart/martservice?query=<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Query><Query  virtualSchemaName = "default" formatter = "TSV" header = "0" uniqueRows = "0" count = "" datasetConfigVersion = "0.6" ><Dataset name = "mmulatta_gene_ensembl" interface = "default" ><Attribute name = "chromosome_name" /><Attribute name = "band" /><Attribute name = "ensembl_gene_id" /></Dataset></Query>'

wget -O Bands_Macaca_mulatta_Ensembl_Marton 'http://www.ensembl.org/biomart/martservice?query=<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Query><Query  virtualSchemaName = "default" formatter = "TSV" header = "0" uniqueRows = "0" count = "" datasetConfigVersion = "0.6" ><Dataset name = "mmulatta_gene_ensembl" interface = "default" ><Attribute name = "chromosome_name" /><Attribute name = "band" /><Attribute name = "uniprot_genename" /></Dataset></Query>'

wget -O Bands_Macaca_mulatta_Ensembl_Marton 'http://www.ensembl.org/biomart/martservice?query=<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Query><Query  virtualSchemaName = "default" formatter = "TSV" header = "0" uniqueRows = "0" count = "" datasetConfigVersion = "0.6" ><Dataset name = "mmulatta_gene_ensembl" interface = "default" ><Attribute name = "chromosome_name" /><Attribute name = "band" /><Attribute name = "hgnc_symbol" /></Dataset></Query>'

wget -O Bands_Mus_musculus_Ensembl_Marton '<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Query><Query  virtualSchemaName = "default" formatter = "TSV" header = "0" uniqueRows = "0" count = "" datasetConfigVersion = "0.6" ><Dataset name = "mmusculus_gene_ensembl" interface = "default" ><Attribute name = "chromosome_name" /><Attribute name = "band" /><Attribute name = "ensembl_gene_id" /></Dataset></Query>'

wget -O Bands_Mus_musculus_Ensembl_Marton 'http://www.ensembl.org/biomart/martservice?query=<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Query><Query  virtualSchemaName = "default" formatter = "TSV" header = "0" uniqueRows = "0" count = "" datasetConfigVersion = "0.6" ><Dataset name = "mmusculus_gene_ensembl" interface = "default" ><Attribute name = "chromosome_name" /><Attribute name = "band" /><Attribute name = "uniprot_genename" /></Dataset></Query>'

wget -O Bands_Mus_musculus_Ensembl_Marton 'http://www.ensembl.org/biomart/martservice?query=<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Query><Query  virtualSchemaName = "default" formatter = "TSV" header = "0" uniqueRows = "0" count = "" datasetConfigVersion = "0.6" ><Dataset name = "mmusculus_gene_ensembl" interface = "default" ><Attribute name = "chromosome_name" /><Attribute name = "band" /><Attribute name = "hgnc_symbol" /></Dataset></Query>'

wget -O Bands_Rattus_norvegicus_Ensembl_Marton 'http://www.ensembl.org/biomart/martservice?query=<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Query><Query  virtualSchemaName = "default" formatter = "TSV" header = "0" uniqueRows = "0" count = "" datasetConfigVersion = "0.6" ><Dataset name = "rnorvegicus_gene_ensembl" interface = "default" ><Attribute name = "chromosome_name" /><Attribute name = "band" /><Attribute name = "ensembl_gene_id" /></Dataset></Query>'

wget -O Bands_Rattus_norvegicus_Ensembl_Marton 'http://www.ensembl.org/biomart/martservice?query=<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Query><Query  virtualSchemaName = "default" formatter = "TSV" header = "0" uniqueRows = "0" count = "" datasetConfigVersion = "0.6" ><Dataset name = "rnorvegicus_gene_ensembl" interface = "default" ><Attribute name = "chromosome_name" /><Attribute name = "band" /><Attribute name = "uniprot_genename" /></Dataset></Query>'

#wget -O Bands_Rattus_norvegicus_Ensembl_Marton 'http://www.ensembl.org/biomart/martservice?query=<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Query><Query  virtualSchemaName = "default" formatter = "TSV" header = "0" uniqueRows = "0" count = "" datasetConfigVersion = "0.6" ><Dataset name = "rnorvegicus_gene_ensembl" interface = "default" ><Attribute name = "chromosome_name" /><Attribute name = "band" /><Attribute name = "hgnc_symbol" /></Dataset></Query>'

wget -O Bands_Xenopus_tropicalis_Ensembl_Marton 'http://www.ensembl.org/biomart/martservice?query=<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Query><Query  virtualSchemaName = "default" formatter = "TSV" header = "0" uniqueRows = "0" count = "" datasetConfigVersion = "0.6" ><Dataset name = "xtropicalis_gene_ensembl" interface = "default" ><Attribute name = "chromosome_name" /><Attribute name = "band" /><Attribute name = "ensembl_gene_id" /></Dataset></Query>'

wget -O Bands_Xenopus_tropicalis_Ensembl_Marton 'http://www.ensembl.org/biomart/martservice?query=<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Query><Query  virtualSchemaName = "default" formatter = "TSV" header = "0" uniqueRows = "0" count = "" datasetConfigVersion = "0.6" ><Dataset name = "xtropicalis_gene_ensembl" interface = "default" ><Attribute name = "chromosome_name" /><Attribute name = "band" /><Attribute name = "uniprot_genename" /></Dataset></Query>'

wget -O Bands_Xenopus_tropicalis_Ensembl_Marton 'http://www.ensembl.org/biomart/martservice?query=<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Query><Query  virtualSchemaName = "default" formatter = "TSV" header = "0" uniqueRows = "0" count = "" datasetConfigVersion = "0.6" ><Dataset name = "xtropicalis_gene_ensembl" interface = "default" ><Attribute name = "chromosome_name" /><Attribute name = "band" /><Attribute name = "hgnc_symbol" /></Dataset></Query>'

wget -O Bands_Danio_rerio_Ensembl_Marton 'http://www.ensembl.org/biomart/martservice?query=<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Query><Query  virtualSchemaName = "default" formatter = "TSV" header = "0" uniqueRows = "0" count = "" datasetConfigVersion = "0.6" ><Dataset name = "drerio_gene_ensembl" interface = "default" ><Attribute name = "chromosome_name" /><Attribute name = "band" /><Attribute name = "ensembl_gene_id" /></Dataset></Query>'

wget -O Bands_Danio_rerio_Ensembl_Marton 'http://www.ensembl.org/biomart/martservice?query=<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Query><Query  virtualSchemaName = "default" formatter = "TSV" header = "0" uniqueRows = "0" count = "" datasetConfigVersion = "0.6" ><Dataset name = "drerio_gene_ensembl" interface = "default" ><Attribute name = "chromosome_name" /><Attribute name = "band" /><Attribute name = "uniprot_genename" /></Dataset></Query>'

wget -O Bands_Danio_rerio_Ensembl_Marton 'http://www.ensembl.org/biomart/martservice?query=<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Query><Query  virtualSchemaName = "default" formatter = "TSV" header = "0" uniqueRows = "0" count = "" datasetConfigVersion = "0.6" ><Dataset name = "drerio_gene_ensembl" interface = "default" ><Attribute name = "chromosome_name" /><Attribute name = "band" /><Attribute name = "hgnc_symbol" /></Dataset></Query>'

wget -O Bands_Drosophila_melanogaster_Ensembl_Marton 'http://www.ensembl.org/biomart/martservice?query=<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Query><Query  virtualSchemaName = "default" formatter = "TSV" header = "0" uniqueRows = "0" count = "" datasetConfigVersion = "0.6" ><Dataset name = "dmelanogaster_gene_ensembl" interface = "default" ><Attribute name = "chromosome_name" /><Attribute name = "band" /><Attribute name = "ensembl_gene_id" /></Dataset></Query>'

#wget -O Bands_Drosophila_melanogaster_Ensembl_Marton 'http://www.ensembl.org/biomart/martservice?query=<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Query><Query  virtualSchemaName = "default" formatter = "TSV" header = "0" uniqueRows = "0" count = "" datasetConfigVersion = "0.6" ><Dataset name = "dmelanogaster_gene_ensembl" interface = "default" ><Attribute name = "chromosome_name" /><Attribute name = "band" /><Attribute name = "uniprot_genename" /></Dataset></Query>'

#wget -O Bands_Drosophila_melanogaster_Ensembl_Marton 'http://www.ensembl.org/biomart/martservice?query=<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Query><Query  virtualSchemaName = "default" formatter = "TSV" header = "0" uniqueRows = "0" count = "" datasetConfigVersion = "0.6" ><Dataset name = "dmelanogaster_gene_ensembl" interface = "default" ><Attribute name = "chromosome_name" /><Attribute name = "band" /><Attribute name = "hgnc_symbol" /></Dataset></Query>'

wget -O Bands_Caenorhabditis_elegans_Ensembl_Marton 'http://www.ensembl.org/biomart/martservice?query=<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Query><Query  virtualSchemaName = "default" formatter = "TSV" header = "0" uniqueRows = "0" count = "" datasetConfigVersion = "0.6" ><Dataset name = "celegans_gene_ensembl" interface = "default" ><Attribute name = "chromosome_name" /><Attribute name = "band" /><Attribute name = "ensembl_gene_id" /></Dataset></Query>'

wget -O Bands_Caenorhabditis_elegans_Ensembl_Marton 'http://www.ensembl.org/biomart/martservice?query=<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Query><Query  virtualSchemaName = "default" formatter = "TSV" header = "0" uniqueRows = "0" count = "" datasetConfigVersion = "0.6" ><Dataset name = "celegans_gene_ensembl" interface = "default" ><Attribute name = "chromosome_name" /><Attribute name = "band" /><Attribute name = "uniprot_genename" /></Dataset></Query>'

#wget -O Bands_Caenorhabditis_elegans_Ensembl_Marton 'http://www.ensembl.org/biomart/martservice?query=<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Query><Query  virtualSchemaName = "default" formatter = "TSV" header = "0" uniqueRows = "0" count = "" datasetConfigVersion = "0.6" ><Dataset name = "celegans_gene_ensembl" interface = "default" ><Attribute name = "chromosome_name" /><Attribute name = "band" /><Attribute name = "hgnc_symbol" /></Dataset></Query>'

wget -O Bands_Saccharomyces_cerevisiae_Ensembl_Marton 'http://www.ensembl.org/biomart/martservice?query=<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Query><Query  virtualSchemaName = "default" formatter = "TSV" header = "0" uniqueRows = "0" count = "" datasetConfigVersion = "0.6" ><Dataset name = "scerevisiae_gene_ensembl" interface = "default" ><Attribute name = "chromosome_name" /><Attribute name = "band" /><Attribute name = "ensembl_gene_id" /></Dataset></Query>'

#wget -O Bands_Saccharomyces_cerevisiae_Ensembl_Marton 'http://www.ensembl.org/biomart/martservice?query=<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Query><Query  virtualSchemaName = "default" formatter = "TSV" header = "0" uniqueRows = "0" count = "" datasetConfigVersion = "0.6" ><Dataset name = "scerevisiae_gene_ensembl" interface = "default" ><Attribute name = "chromosome_name" /><Attribute name = "band" /><Attribute name = "uniprot_genename" /></Dataset></Query>'

#wget -O Bands_Saccharomyces_cerevisiae_Ensembl_Marton 'http://www.ensembl.org/biomart/martservice?query=<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Query><Query  virtualSchemaName = "default" formatter = "TSV" header = "0" uniqueRows = "0" count = "" datasetConfigVersion = "0.6" ><Dataset name = "scerevisiae_gene_ensembl" interface = "default" ><Attribute name = "chromosome_name" /><Attribute name = "band" /><Attribute name = "hgnc_symbol" /></Dataset></Query>'